-- AlterTable
ALTER TABLE "JobLedgerEntry"
  ADD COLUMN "inputS3Uris" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "outputS3Uri" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "connectionId" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "roleArn" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "region" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "s3Endpoint" TEXT;
