// Pure codegen helper shared between the Vite plugin and the CLI.
// Takes a CYTARIO_PLUGINS env string, returns the deterministic
// contents of `app/plugins.generated.ts`.

const NPM_NAME_RE = /^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/;

export interface CodegenInput {
  plugins: readonly string[];
}

export class InvalidPluginNameError extends Error {
  override readonly name = "InvalidPluginNameError";
}

/** Validate + parse the CYTARIO_PLUGINS env var. Invalid entries throw. */
export function parseCytarioPluginsEnv(env: string | undefined): CodegenInput {
  const raw = (env ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  for (const name of raw) {
    if (!NPM_NAME_RE.test(name)) {
      throw new InvalidPluginNameError(
        `Invalid npm package name in CYTARIO_PLUGINS: ${JSON.stringify(name)}`,
      );
    }
  }
  return { plugins: raw };
}

/**
 * Emit the contents of `app/plugins.generated.ts`. Identifiers are
 * derived by index so the raw env value never lands as a bare identifier.
 */
export function generatePluginsModule(input: CodegenInput): string {
  const { plugins } = input;
  const imports = plugins
    .map((name, i) => `import plugin_${i} from ${JSON.stringify(name)};`)
    .join("\n");
  const list = plugins.map((_, i) => `  plugin_${i},`).join("\n");

  return `// AUTOGENERATED by vite-plugins/cytario-plugins.ts — do not edit.
// Run \`npm run codegen\` (or rebuild) to regenerate.
// See README.md "Plugin model" for the contract.

import type { CytarioPlugin, Logger, PluginContext } from "@cytario/plugin-api";
import {
  assertApiCompatible,
  IncompatiblePluginError,
  hostApiVersion,
} from "@cytario/plugin-api";
import { formatRegistry } from "~/components/ImageViewer/state/formatRegistry";
${imports ? "\n" + imports : ""}


const plugins: ReadonlyArray<CytarioPlugin> = [
${list}
];

// Built-in formats register inside ViewerStoreContext (client-only).
// Not imported here — viv/geotiff would break the SSR bundle.
export async function bootstrapPlugins(logger: Logger): Promise<void> {
  for (const plugin of plugins) {
    try {
      assertApiCompatible(plugin, hostApiVersion);
    } catch (err) {
      const message =
        err instanceof IncompatiblePluginError
          ? err.message
          : err instanceof Error
            ? err.message
            : String(err);
      logger.error(\`Skipping incompatible plugin "\${plugin?.name ?? "<unknown>"}"\`, {
        error: message,
      });
      continue;
    }

    const ctx: PluginContext = {
      logger,
      formats: formatRegistry.scopedFor(plugin.name),
    };

    try {
      await plugin.register(ctx);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error(\`Plugin "\${plugin.name}" register() threw — skipping\`, {
        error: message,
      });
    }
  }
}
`;
}

// Kept out of `app/.generated/` — that path is owned by `prisma generate`.
export const GENERATED_PATH = "app/plugins.generated.ts";
