// AUTOGENERATED by vite-plugins/cytario-plugins.ts — do not edit.
// Run `npm run codegen` (or rebuild) to regenerate.
// See README.md "Plugin model" for the contract.

import type { CytarioPlugin, Logger } from "@cytario/plugin-api";
import type { BootstrapRegistries } from "~/lib/bootstrapPluginsCore";
import { bootstrapPluginsCore } from "~/lib/bootstrapPluginsCore";



const plugins: ReadonlyArray<CytarioPlugin> = [

];

// Built-in formats register inside ViewerStoreContext (client-only).
// Not imported here — viv/geotiff would break the SSR bundle.
export function bootstrapPlugins(
  logger: Logger,
  registries?: BootstrapRegistries,
): Promise<void> {
  return bootstrapPluginsCore(plugins, logger, registries);
}
