#!/usr/bin/env node
/* global console */
// Sync src/version.ts with package.json#version. Runs as a prebuild step
// so the host's hostApiVersion constant always matches the published
// package version. Invoked from `npm run build` and indirectly by the
// `@semantic-release/exec` prepareCmd in the release workflow.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_PATH = resolve(HERE, "..", "package.json");
const VERSION_PATH = resolve(HERE, "..", "src", "version.ts");

const pkg = JSON.parse(readFileSync(PKG_PATH, "utf8"));
if (typeof pkg.version !== "string" || pkg.version.length === 0) {
  throw new Error(`Missing or empty "version" field in ${PKG_PATH}`);
}

const out =
  "// Generated by scripts/write-version.mjs at build time.\n" +
  "// Source of truth: packages/plugin-api/package.json.\n" +
  `export const hostApiVersion: string = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(VERSION_PATH, out, "utf8");
console.log(`[plugin-api] wrote version ${pkg.version} → src/version.ts`);
