#!/usr/bin/env node
/* global console, process */
/**
 * Regenerate `src/version.ts` so `hostApiVersion` reflects the latest
 * published version of @cytario/plugin-api.
 *
 * Resolution order:
 *
 *   1. The most recent `plugin-api-v*` git tag, stripped of its prefix.
 *      This is the source of truth post-release because we deliberately
 *      do NOT run `@semantic-release/git` to commit the bumped version
 *      back to the repo (per the semantic-release FAQ on commit-during-
 *      release antipatterns and to avoid a race between the host and
 *      plugin-api release workflows on shared main branch pushes).
 *
 *   2. `package.json#version` as a fallback for:
 *        - the first release (no tag yet);
 *        - in-progress releases, where `@semantic-release/npm` has
 *          mutated package.json#version in the working tree but no tag
 *          has been pushed yet;
 *        - fresh clones with insufficient git depth to see tags.
 *
 * The script is idempotent — it writes nothing when the resolved
 * version already matches the value committed in `src/version.ts`. This
 * keeps vite HMR quiet during local dev and avoids spurious
 * working-tree dirt in CI typecheck runs.
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_PATH = resolve(HERE, "..", "package.json");
const VERSION_PATH = resolve(HERE, "..", "src", "version.ts");
const REPO_ROOT = resolve(HERE, "..", "..", "..");

function resolveFromGitTag() {
  try {
    const out = execSync(
      'git describe --tags --match="plugin-api-v*" --abbrev=0',
      { cwd: REPO_ROOT, stdio: ["ignore", "pipe", "ignore"] },
    )
      .toString()
      .trim();
    if (out.startsWith("plugin-api-v")) return out.replace(/^plugin-api-v/, "");
    return null;
  } catch {
    return null;
  }
}

function resolveVersion() {
  const fromTag = resolveFromGitTag();
  if (fromTag) return { version: fromTag, source: "git tag" };

  const pkg = JSON.parse(readFileSync(PKG_PATH, "utf8"));
  if (typeof pkg.version !== "string" || pkg.version.length === 0) {
    throw new Error(`Missing or empty "version" field in ${PKG_PATH}`);
  }
  return { version: pkg.version, source: "package.json" };
}

function renderFile(version) {
  return (
    "// Generated by scripts/write-version.mjs at build time.\n" +
    "// Resolved from the latest `plugin-api-v*` git tag, with\n" +
    "// `package.json#version` as a fallback. Do not edit by hand.\n" +
    `export const hostApiVersion: string = ${JSON.stringify(version)};\n`
  );
}

const { version, source } = resolveVersion();
const next = renderFile(version);

let current = "";
try {
  current = readFileSync(VERSION_PATH, "utf8");
} catch {
  // First write — no existing file.
}

if (current === next) {
  if (process.env.PLUGIN_API_WRITE_VERSION_VERBOSE) {
    console.log(`[plugin-api] version ${version} (${source}) unchanged`);
  }
} else {
  writeFileSync(VERSION_PATH, next, "utf8");
  console.log(
    `[plugin-api] wrote version ${version} (${source}) → src/version.ts`,
  );
}
