// Generated by scripts/write-version.mjs at build time.
// Resolved from the latest `plugin-api-v*` git tag, with
// `package.json#version` as a fallback. Do not edit by hand.
export const hostApiVersion: string = "2.0.4";
